### ISSUE TITLE
Problems decoding events

### ISSUE THREAD

**Issue by AlexCheema** [xf00f/web3x#26] opened 2019-02-21 17:33 UTC
Contracts to reproduce:

TransferBug.sol
```solidity
pragma solidity ^0.5.0;

import "openzeppelin-solidity/contracts/math/SafeMath.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/SafeERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC721/IERC721Full.sol";
import "openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol";

contract TransferBug is ERC721Full {

    using SafeERC20 for ERC20;

    constructor() public ERC721Full("transfer bug", "BUG") {
    }

    function testBug(uint256 amount, address tokenAddress) public {
        ERC20 token = ERC20(tokenAddress);
        token.safeTransferFrom(msg.sender, address(this), amount);
    }

}
```

Token.sol
```solidity
pragma solidity ^0.5.0;
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";


contract Token is ERC20 {
    string public name;
    string public symbol;
    uint8 public decimals;
    address public supplier;

    constructor(string memory _name, string memory _symbol, uint8 _decimals, uint256 totalSupply) public {
        name = _name;
        symbol = _symbol;
        decimals = _decimals;
        supplier = msg.sender;

        _mint(supplier, totalSupply);
    }
}
```

Simple test:
```typescript
import { Token } from "../../src/contracts/cos/Token";
import { TransferBug } from "../../src/contracts/cos/TransferBug";
import { startLocalBlockchain } from "../../src/localBlockchain";

test("transferBug", async () => {
  const { eth, accounts } = await startLocalBlockchain({ hostname: "127.0.0.1", port: 8500, findNextPort: true });

  const from = accounts[0].address;

  const token = new Token(eth);
  await token
    .deploy("test", "TEST", 18, 10000000)
    .send({ from, gas: 40000000 })
    .getReceipt();
  const originalBalance = await token.methods.balanceOf(from).call();
  console.log("Original balance", originalBalance);

  const buggedContract = new TransferBug(eth);
  await buggedContract
    .deploy()
    .send({ from, gas: 40000000 })
    .getReceipt();

  console.log("Test contract addr", buggedContract.address);

  await token.methods
    .approve(buggedContract.address!, 10)
    .send({ from, gas: 40000000 })
    .getReceipt();

  const result = await buggedContract.methods
    .testBug(10, token.address!)
    .send({ from, gas: 40000000 })
    .getReceipt();
  console.log("Got test reuslt", result);
});
```

Error:
```
    Returned values aren't valid, did it run Out of Gas?

      at ABICoder.decodeParameters (node_modules/src/contract/abi-coder/index.ts:128:13)
      at ABICoder.decodeParameter (node_modules/src/contract/abi-coder/index.ts:115:17)
      at inputs.forEach (node_modules/src/contract/abi-coder/index.ts:177:20)
          at Array.forEach (<anonymous>)
      at ABICoder.decodeLog (node_modules/src/contract/abi-coder/index.ts:172:7)
      at Object.decodeEvent (node_modules/src/contract/decode-event-abi.ts:36:34)
      at ContractEventEntry.decodeEvent (node_modules/src/contract/abi/contract-event-entry.ts:62:12)
      at ContractAbi.decodeAnyEvent (node_modules/src/contract/abi/contract-abi.ts:47:4)
      at receipt.logs.map.log (node_modules/src/contract/sent-contract-tx.ts:38:25)
          at Array.map (<anonymous>)
      at SentContractTx.handleReceipt (node_modules/src/contract/sent-contract-tx.ts:38:25)
```

I logged the topics for the Transfer event:
```
[ '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x000000000000000000000000627306090abab3a6e1400e9345bc60c78a8bef57',
      '0x000000000000000000000000f12b5dd4ead5f743c6baa640b0216200e89b60da' ]
```

Looks like it is missing one topic. It is not anonymous, so it should have four: one for the hash of the signature and three for the parameters:
```solidity
event Transfer(address indexed from, address indexed to, uint256 value);
```

This causes this line to fail because the 4th topic is not there: https://github.com/xf00f/web3x/blob/master/src/contract/abi-coder/index.ts#L176

**Comment by charlielye** [comment] 2019-02-22 00:22
@AlexCheema This is an interesting issue you've uncovered.
The problem is not a missing topic exactly. Only indexed parameters are topics.
You call an ERC721 contract. The interface defines the Transfer event as follows.
```
event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);
```
Your ERC721 contract then calls an ERC20 contract which creates a Transfer event with signature:
```
event Transfer(address indexed from, address indexed to, uint256 value);
```
These are two separate events. Normally, the fact that each event has its own signature, would mean the log created by the called contract would not have a matching signature, and it would be treated as an anonymous event. This is the correct and expected behaviour in this case. However, both of these events have their signature derived from the standardised signature format resulting in `Transfer(address,address,uint256)`, and thus their signatures match.

The client code then attempts to parse the ERC20 Transfer event as a ERC721 Transfer event, and a topic is missing because the ERC20 event does not have an indexed `value`.

I think you are incorrectly expecting a log event of one type to be exposed as another type. The best you can hope for here is an anonymous event, otherwise you would end up with a `value` in a `tokenId`.

Regardless, there does seem to be a library issue in that it is parsing an event from one contract as if it belongs to another. I believe the solution is check that any returned logs belong to the current contract and if not they must be treated anonymous.

I will try and fix this shortly.

**Comment by xf00f** [comment] 2019-02-22 00:23
@AlexCheema This is an interesting issue you've uncovered.
The problem is not a missing topic exactly. Only indexed parameters are topics.
You call an ERC721 contract. The interface defines the Transfer event as follows.

```
event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);
```
Your ERC721 contract then calls an ERC20 contract which creates a Transfer event with signature:

```
event Transfer(address indexed from, address indexed to, uint256 value);
```
These are two separate events. Normally, the fact that each event has its own signature, would mean the log created by the called contract would not have a matching signature, and it would be treated as an anonymous event. This is the correct and expected behaviour in this case. However, both of these events have their signature derived from the standardised signature format resulting in `Transfer(address,address,uint256)`, and thus their signatures match.

The client code then attempts to parse the ERC20 Transfer event as a ERC721 Transfer event, and a topic is missing because the ERC20 event does not have an indexed `value`.

I think you are incorrectly expecting a log event of one type to be exposed as another type. The best you can hope for here is an anonymous event, otherwise you would end up with a `value` in a `tokenId`.

Regardless, there does seem to be a library issue in that it is parsing an event from one contract as if it belongs to another. I believe the solution is check that any returned logs belong to the current contract and if not they must be treated anonymous.

I will try and fix this shortly.

**Comment by xf00f** [comment] 2019-02-23 16:26
@AlexCheema v3.0.3 should fix your problem

Given the test case above, you will find that there are no events because `TransferBug` does not generate any events. The raw event log generated by the ERC20 token call will be in a field named `anonymousLogs`.

Hope this solves your problem.

**Closed by xf00f** 2019-02-23 16:26 UTC
