### ISSUE TITLE
lack of dependencies for @types/ws and net

### ISSUE THREAD

**Issue by studioTeaTwo** [xf00f/web3x#2] opened 2018-10-15 01:32 UTC
This is awsome PJ!

I tried `web3x-es`, then got compile errors.
It resolved after installing `@types/ws` and `net`.

```
ERROR in node_modules/web3x-es/providers/ws.d.ts(6,23): error TS2688: Cannot find type definition file for 'ws'.
node_modules/web3x-es/providers/ws.d.ts(7,10): error TS2305: Module '"/client/node_modules/isomorphic-ws/index"' has no exported member 'ClientOptions'.
node_modules/web3x-es/providers/ws.d.ts(7,31): error TS2497: Module '"/client/node_modules/isomorphic-ws/index"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by xf00f** [comment] 2018-10-15 15:17
Hello.

If you are using webpack to build for the browser, it's currently necessary to specify:
```
  node: {
    net: 'empty',
  },
```
in your webpack.js file. This prevents the IpcProvider (which only works in node.js) from failing the compile. Adding `net` is another solution but will increase the size of your build.

As for the `@types/ws` I think the issue is I have it listed as a devDependency, however I never saw this issue in my own environment. Can I ask how you are using the library?

**Comment by studioTeaTwo** [comment] 2018-10-16 08:02
@xf00f 
Thank you! I understand.

I use Angular. So cli build tool configures node. 
I do like this, then OK!
https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d#gistcomment-2599550

**Comment by studioTeaTwo** [comment] 2018-10-16 15:08
I forgot to describe about `@types/ws`.
It remains error with above settings.
I guess that is why I do such as `import { HttpProvider } from 'web3x-es/providers'` in my ts files.

**Comment by xf00f** [comment] 2018-10-16 21:01
@studioTeaTwo 

I have deployed version 1.0.3 which adds `ws` as a dependency. `isomorphic-ws` has a peerDependency on `ws`, which if not explicitly installed results in a warning during package installation. I'm not sure if this is leading to your issue with `@types/ws` as that's a different package, but would appreciate you letting me know if new version fixes that problem.

If not, perhaps I just need to make `@types/ws` a dependency.

**Comment by studioTeaTwo** [comment] 2018-10-17 10:03
@xf00f 

Thanks for ver1.0.3.
I tried it, but it unfortunately remains the same errors as issue description.

The package.json that I use is like below.(also do `npm postinstall` which is described on the comment above.)

```
  "dependencies": {
    "@angular/animations": "^7.0.0-rc.1",
    "@angular/common": "^7.0.0-rc.1",
    "@angular/compiler": "^7.0.0-rc.1",
    "@angular/core": "^7.0.0-rc.1",
    "@angular/forms": "^7.0.0-rc.1",
    "@angular/http": "^7.0.0-rc.1",
    "@angular/platform-browser": "^7.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^7.0.0-rc.1",
    "@angular/router": "^7.0.0-rc.1",
    "angular2-qrcode": "^2.0.1",
    "core-js": "^2.5.4",
    "loom-js": "^1.27.0",
    "rxjs": "~6.3.3",
    "web3x-es": "^1.0.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.5",
    "@angular/compiler-cli": "^7.0.0-rc.1",
    "@angular/language-service": "^7.0.0-rc.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "truffle-contract": "^3.0.6",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.3"
  }
```

And the usage of `web3x-es` is like below.

```we3service.ts
import { Web3 } from 'web3x-es';
import { HttpProvider } from 'web3x-es/providers';

~~~~~~

  bootstrapWeb3(): void {
    if (typeof window.web3 !== 'undefined') {
      this.web3 = new Web3(window.web3.currentProvider);
    } else {
      this.web3 = new Web3(new HttpProvider('http://localhost:8545'));
    }
  }
```

If I remove `import { HttpProvider } from 'web3x-es/providers';`, the compile succeed.

**Comment by xf00f** [comment] 2018-10-17 17:36
@studioTeaTwo 

I have deployed 1.0.4. This moves @types/* dependencies from `devDependencies` to `dependencies`.
This should mean you get @types/ws installed as part of installing web3x.
Please try again with this version.

**Comment by studioTeaTwo** [comment] 2018-10-18 07:38
@xf00f 
I tried `v1.0.4`. So `@types/ws` fixed!
But new problem of compile occurred like below.

```
ERROR in node_modules/web3x-es/utils/bn.d.ts(1,9): error TS2305: Module '"/client/node_modules/@types/bn.js/index"' has no exported member 'BN'.
node_modules/web3x-es/utils/bn.d.ts(1,18): error TS2497: Module '"/client/node_modules/@types/bn.js/index"' resolves to a non-module entity and cannot be imported using this construct.
node_modules/web3x-es/utils/hex.d.ts(1,8): error TS1192: Module '"/client/node_modules/@types/bn.js/index"' has no default export.
node_modules/web3x-es/utils/units-ethjs-unit.d.ts(1,8): error TS1192: Module '"/client/node_modules/@types/bn.js/index"' has no default export.
node_modules/web3x-es/utils/units.d.ts(1,8): error TS1192: Module '"/client/node_modules/@types/bn.js/index"' has no default export.
```

There is `import { toWei } from 'web3x-es/utils'` in my `.ts`.
This did not occur before `1.0.4`.

**Comment by xf00f** [comment] 2018-10-18 11:07
@studioTeaTwo 
Please try adding `"allowSyntheticDefaultImports": true` to your `tsconfig.json` file.
I will see if there is a way to avoid this step in a new version.

**Comment by studioTeaTwo** [comment] 2018-10-19 03:09
@xf00f 
I did it on `1.0.4`, then OK!
I added not only `"allowSyntheticDefaultImports": true` but also `"esModuleInterop": true`.

**Comment by xf00f** [comment] 2018-10-19 09:49
@studioTeaTwo 
Great. Closing this issue. A new version will be out soon that fixes a couple more bugs, and should result in much smaller builds in some cases (i.e. if you are only interfacing with MetaMask, and not using local storage accounts).

If you have other issues let me know. Also, if there are use cases where this library isn't serving your needs and you find you need another library, let me know. I want this library to serve as many use cases as possible.

**Closed by xf00f** 2018-10-19 09:49 UTC
